import polygonIcon from "../assets/icon-polygon.svg";
import avalancheIcon from "../assets/icon-avalanche.svg";
import { addChain, switchChain } from "./chainConnect";

// Chain Icons
import avaxChainIcon from "../assets/chainIcons/avalanche.svg";
import polygonChainIcon from "../assets/chainIcons/polygon.svg";

const supportedChains = {
  80001: {
    id: "matic-network",
    label: "Polygon Testnet",
    chain: "Polygon",
    icon: polygonIcon,
    symbol: "MATIC",
    explorer: "https://mumbai.polygonscan.com/",
    networkId: 80001,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=matic-network&vs_currencies=usd",
    add: addChain,
    isMainnet: false,
    switch: switchChain,
    coinGeckoLabel: "matic-network",
  },
  137: {
    id: "matic-network",
    label: "Polygon",
    chain: "Polygon",
    explorer: "https://polygonscan.com/",
    icon: polygonIcon,
    symbol: "MATIC",
    networkId: 137,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=matic-network&vs_currencies=usd",
    add: addChain,
    isMainnet: true,
    switch: switchChain,
    coinGeckoLabel: "matic-network",
  },
  43114: {
    id: "avalanche",
    label: "Avalanche",
    chain: "Avalanche",
    icon: avalancheIcon,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=avalanche-2&vs_currencies=usd",
    symbol: "AVAX",
    networkId: 43114,
    explorer: "https://snowtrace.io/",
    add: addChain,
    isMainnet: true,
    switch: switchChain,
    coinGeckoLabel: "avalanche-2",
  },
  43113: {
    id: "avalanche",
    label: "Avalanche Testnet",
    chain: "Avalanche",
    icon: avalancheIcon,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=avalanche-2&vs_currencies=usd",
    symbol: "AVAX",
    networkId: 43113,
    explorer: "https://testnet.snowtrace.io/",
    add: addChain,
    isMainnet: false,
    switch: switchChain,
    coinGeckoLabel: "avalanche-2",
  },
  0: {
    id: "invalid",
    label: "invalid",
    chain: "invalid",
    icon: avalancheIcon,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=avalanche-2&vs_currencies=usd",
    symbol: "invalid",
    networkId: 0,
    explorer: "https://testnet.snowtrace.io/",
    add: addChain,
    isMainnet: false,
    switch: switchChain,
    coinGeckoLabel: "invalid",
  },
};

export const orderedChainsList = [
  {
    id: "matic-network",
    label: "Polygon ",
    chain: "Polygon",
    icon: polygonChainIcon,
    symbol: "MATIC",
    explorer: "https://mumbai.polygonscan.com/address",
    networkId: 80001,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=matic-network&vs_currencies=usd",
    add: addChain,
    isMainnet: false,
    switch: switchChain,
    coinGeckoLabel: "matic-network",
  },
  {
    id: "matic-network",
    label: "Polygon",
    chain: "Polygon",
    explorer: "https://polygonscan.com/address",
    icon: polygonChainIcon,
    symbol: "MATIC",
    networkId: 137,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=matic-network&vs_currencies=usd",
    add: addChain,
    isMainnet: true,
    switch: switchChain,
    coinGeckoLabel: "matic-network",
  },
  {
    id: "avalanche",
    label: "Avalanche",
    chain: "Avalanche",
    icon: avaxChainIcon,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=avalanche-2&vs_currencies=usd",
    symbol: "AVAX",
    networkId: 43114,
    explorer: "https://snowtrace.io/",
    add: addChain,
    isMainnet: true,
    switch: switchChain,
    coinGeckoLabel: "avalanche-2",
  },
  {
    id: "avalanche",
    label: "Avalanche ",
    chain: "Avalanche",
    icon: avaxChainIcon,
    livePrice: "https://api.coingecko.com/api/v3/simple/price?ids=avalanche-2&vs_currencies=usd",
    symbol: "AVAX",
    networkId: 43113,
    explorer: "https://testnet.snowtrace.io/",
    add: addChain,
    isMainnet: false,
    switch: switchChain,
    coinGeckoLabel: "avalanche-2",
  },
];

export default supportedChains;
